version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/quiz
  mongo:
    image: mongo
    ports:
      - "27017:27017"
